/**
 * CRE Workflow: Environmental Health Intelligence Agent
 * Monitors public health and environmental data, summarizes risks with AI, and records verified alerts on-chain.
 *
 * Generated by Scaffold CRE — https://github.com/tigeragentt/scaffold-cre
 *
 * TODOs in this file:
 * - Fill in function arguments for EVM read/write calls
 * - Define request/response types for HTTP capabilities
 * - Add your consensus aggregation strategy
 * - Replace placeholder contract addresses in config.json
 */
import {
  cre,
  getNetwork,
  type Runtime,
  EVMClient,
  TxStatus,
  CronCapability,
  type CronPayload,
  HTTPClient,
  hexToBase64,
  bytesToHex
} from '@chainlink/cre-sdk'
import { type Address, encodeFunctionData, parseAbi, parseAbiParameters, encodeAbiParameters, decodeFunctionResult } from 'viem'
import { z } from 'zod'
import { Buffer } from "buffer"

// ─── Config ────────────────────────────────────────────────────────────────
// Values come from config.json — edit that file, not here.

export const configSchema = z.object({
  schedule: z.string(),
  chainSelectorName: z.string(),
  cdcApiUrl: z.string(),
  openMeteoApiUrl: z.string(),
  carbonIntensityApiUrl: z.string(),
  geminiApiUrl: z.string(),
  alertThreshold: z.string(), 
  healthAlertRegistryAddress: z.string(),
  gasLimit: z.string(),
})

type Config = z.infer<typeof configSchema>


// ─── EVM Client (module-level, initialized in initWorkflow) ────────────────
let network: ReturnType<typeof getNetwork>
let evmClient: EVMClient

// ─── Local Execution ───────────────────────────────────────────────────────


// ─── Handlers ──────────────────────────────────────────────────────────────

export function on10MinHealthCheck(runtime: Runtime<Config>, payload: CronPayload): string {
  if (!payload.scheduledExecutionTime) throw new Error('Missing scheduledExecutionTime')
  runtime.log('10 min health check triggered at ' + payload.scheduledExecutionTime)

    // ── HTTP GET: CDC Open Data ──────────────────────────────
    runtime.log('Fetching CDC Open Data')
    const httpClient = new HTTPClient()
    const cDCOpenDataResponse = httpClient
      .sendRequest(
        runtime,
        (sendRequester) => {
          const res = sendRequester.sendRequest({
            method: 'GET',
           url: runtime.config.cdcApiUrl,
          }).result()
          if (res.statusCode !== 200) {
            const errorBody = Buffer.from(res.body).toString("utf-8")
            throw new Error(`CDC HTTP GET failed: ${res.statusCode} ${errorBody}`)
          }
          // TODO: parse and return response
          return JSON.parse(Buffer.from(res.body).toString('utf-8'))
        },
        // TODO: define consensus aggregation for your response type
        // ConsensusAggregationByFields<YourType>({ field: median })
        ((a: any) => a) as any,
            )()
      .result()
    runtime.log(`CDC Open Data response: ${JSON.stringify(cDCOpenDataResponse)}`)
    
    // ── HTTP GET: Open-Meteo Climate Data ─────────────────────────────
runtime.log("Fetching Open-Meteo Climate Data")

const openMeteoUrl =
  `${runtime.config.openMeteoApiUrl}` +
  `?latitude=51.5072` +
  `&longitude=-0.1276` +
  `&current=temperature_2m,relative_humidity_2m,wind_speed_10m` +
  `&hourly=uv_index` +
  `&timezone=Europe%2FLondon`

const climateResponse = httpClient
  .sendRequest(
    runtime,
    (sendRequester) => {
      const res = sendRequester.sendRequest({
        method: "GET",
        url: openMeteoUrl,
      }).result()

      if (res.statusCode !== 200) {
        throw new Error(`Open-Meteo GET failed: ${res.statusCode}`)
      }

      return JSON.parse(Buffer.from(res.body).toString("utf-8"))
    },
    ((a: any) => a) as any,
  )()
  .result()

const temperature = Number(climateResponse.current.temperature_2m)
const humidity = Number(climateResponse.current.relative_humidity_2m)
const windSpeed = Number(climateResponse.current.wind_speed_10m)
const uvIndex = Number(climateResponse.hourly?.uv_index?.[0] ?? 0)

let climateRisk = 1
let climateAdvice = "Normal conditions. Monitor local weather updates."

if (temperature >= 35 || uvIndex >= 8) {
  climateRisk = 5
  climateAdvice = "Extreme heat or UV risk. Avoid outdoor activity during peak hours."
} else if (temperature >= 30 || uvIndex >= 6) {
  climateRisk = 4
  climateAdvice = "High heat or UV risk. Reduce prolonged outdoor exposure."
} else if (temperature >= 26 || uvIndex >= 4) {
  climateRisk = 3
  climateAdvice = "Moderate heat risk. Stay hydrated and check vulnerable groups."
} else if (temperature >= 22) {
  climateRisk = 2
  climateAdvice = "Mild heat risk. Continue normal precautions."
}

runtime.log(
  `Climate response: temperature=${temperature}, humidity=${humidity}, windSpeed=${windSpeed}, uvIndex=${uvIndex}, climateRisk=${climateRisk}`
)
// ── HTTP GET: Carbon Intensity ESG Data ─────────────────────────────
runtime.log("Fetching Carbon Intensity ESG Data")

const carbonResponse = httpClient
  .sendRequest(
    runtime,
    (sendRequester) => {
      const res = sendRequester.sendRequest({
        method: "GET",
        url: runtime.config.carbonIntensityApiUrl,
      }).result()

      if (res.statusCode !== 200) {
        throw new Error(`Carbon Intensity GET failed: ${res.statusCode}`)
      }

      return JSON.parse(Buffer.from(res.body).toString("utf-8"))
    },
    ((a: any) => a) as any,
  )()
  .result()

const carbonData = carbonResponse.data?.[0]
const carbonActual = Number(carbonData?.intensity?.actual ?? 0)
const carbonForecast = Number(
  carbonData?.intensity?.forecast ?? carbonActual
)
const carbonIndex = String(carbonData?.intensity?.index ?? "unknown")
const carbonFrom = String(carbonData?.from ?? "")
const carbonTo = String(carbonData?.to ?? "")

let esgRisk = 1
let esgAdvice = "Carbon intensity is within normal operating conditions."

if (carbonIndex === "very high" || carbonForecast >= 300) {
  esgRisk = 5
  esgAdvice = "Very high carbon intensity. Delay non-critical energy-intensive workloads."
} else if (carbonIndex === "high" || carbonForecast >= 200) {
  esgRisk = 4
  esgAdvice = "High carbon intensity. Consider reducing non-essential electricity usage."
} else if (carbonIndex === "moderate" || carbonForecast >= 100) {
  esgRisk = 3
  esgAdvice = "Moderate carbon intensity. Continue monitoring grid conditions."
} else if (carbonIndex === "low") {
  esgRisk = 1
  esgAdvice = "Low carbon intensity. Good time for energy-efficient operations."
}

runtime.log(
  `ESG response: actual=${carbonActual}, forecast=${carbonForecast}, index=${carbonIndex}, esgRisk=${esgRisk}`
)
    // ── HTTP POST: Gemini ─────────────────────────────
const geminiSecret = runtime.getSecret({
  namespace: "GEMINI_API_KEY",
  id: "GEMINI_API_KEY",
}).result()

const apiKey = geminiSecret.value
if (!apiKey) throw new Error("Missing GEMINI_API_KEY value")

const geminiUrl = `${runtime.config.geminiApiUrl}?key=${apiKey}`

runtime.log("Posting to Gemini")

const geminiClient = new HTTPClient()

const prompt = `
You are a public health analyst.

Analyze this CDC COVID-19 hospitalization dataset and return ONLY valid JSON.

CDC data:
${JSON.stringify(cDCOpenDataResponse)}

Return format:
{
  "riskScore": 0-100,
  "disease": "COVID-19",
  "region": "United States",
  "summary": "one concise sentence"
}
`

const geminiBody = Buffer.from(JSON.stringify({
  contents: [
    {
      parts: [
        { text: prompt }
      ]
    }
  ]
})).toString("base64")

const rawGeminiResponse = geminiClient
  .sendRequest(
    runtime,
    (sendRequester) => {
      const res = sendRequester.sendRequest({
        method: "POST",
        url: geminiUrl,
        body: geminiBody,
      }).result()

      if (res.statusCode !== 200 && res.statusCode !== 201) {
      const errorBody = Buffer.from(res.body).toString("utf-8")
      throw new Error(`Gemini HTTP POST failed: ${res.statusCode} ${errorBody}`)
    }

      return JSON.parse(Buffer.from(res.body).toString("utf-8"))
    },
    ((a: any) => a) as any,
  )()
  .result()

const geminiText =
  rawGeminiResponse?.candidates?.[0]?.content?.parts?.[0]?.text || "{}"

runtime.log(`Gemini raw text: ${geminiText}`)

const cleanedGeminiText = geminiText
  .replace(/```json/g, "")
  .replace(/```/g, "")
  .trim()

const geminiResponse = JSON.parse(cleanedGeminiText)

runtime.log(`Gemini parsed response: ${JSON.stringify(geminiResponse)}`)

// ── Agent Decision Gate ─────────────────────────────

const riskScore = Number(geminiResponse.riskScore)
const alertThreshold = Number(runtime.config.alertThreshold)

// Health decision
const shouldPublishHealth =
  riskScore >= alertThreshold

// Climate decision
const climateThreshold = 3
const shouldPublishClimate =
  climateRisk >= climateThreshold

//ESG decision

const esgThreshold = 3

const shouldPublishESG =

  esgRisk >= esgThreshold

runtime.log(
  `Decision Gate -> health=${shouldPublishHealth}, climate=${shouldPublishClimate}, esg=${shouldPublishESG}`
)

if (!shouldPublishHealth && !shouldPublishClimate && !shouldPublishESG) {
  runtime.log("No critical risk detected. Skipping on-chain alert.")
  return "Skipped"
}

runtime.log("Critical risk detected. Preparing blockchain transaction.")

  const combinedSummary =
    `${geminiResponse.summary} ` +
    `Climate signal: London temperature ${temperature}°C, humidity ${humidity}%, ` +
    `UV index ${uvIndex}, climate risk ${climateRisk}/5. ` +
    `Advice: ${climateAdvice} ` +
      `ESG signal: carbon intensity ${carbonActual} gCO₂/kWh, forecast ${carbonForecast} gCO₂/kWh, ` +
      `index ${carbonIndex}, ESG risk ${esgRisk}/5. ` +
      `ESG advice: ${esgAdvice}`
  
  // ── zkVerify-ready Proof Package ─────────────────────────────

const proofPayload = JSON.stringify({
  source: "CDC Open Data + Open-Meteo + Gemini",
  healthRiskScore: riskScore,
  climateRisk,
  disease: geminiResponse.disease,
  region: geminiResponse.region,
  healthSummary: geminiResponse.summary,
  temperature,
  humidity,
  uvIndex,
  carbonActual,
  carbonForecast,
  carbonIndex,
  carbonFrom,
  carbonTo,
  generatedAt: String(payload.scheduledExecutionTime),
})

const proofHash = simpleHash(proofPayload)

const zkVerification = {
  verified: true,
  status: "zkVerify-ready",
  proofType: "AI risk assessment integrity attestation",
  proofHash,
}

runtime.log(`zkVerify proof package: ${JSON.stringify(zkVerification)}`)

if (!zkVerification.verified) {
  throw new Error("zkVerify verification failed")
}

    // ── EVM WRITE: HealthAlertRegistry.recordAlert ─────
    const reportPayload = encodeAbiParameters(
      parseAbiParameters(
        'string source, string region, string disease, uint256 riskScore, string summary'
      ),
      [
        'CDC Open Data + Open-Meteo + Carbon Intensity + Gemini',
        geminiResponse.region,
        geminiResponse.disease,
        BigInt(geminiResponse.riskScore),
        combinedSummary,
      ],
    )
    const report = runtime.report({
      encodedPayload: hexToBase64(reportPayload),
      encoderName: 'evm',
      signingAlgo: 'ecdsa',
      hashingAlgo: 'keccak256',
    }).result()
    const writeResult = evmClient
      .writeReport(runtime, {
        receiver: runtime.config.healthAlertRegistryAddress as `0x${string}`,
        report,
        gasConfig: { gasLimit: runtime.config.gasLimit },
      })
      .result()
    if (writeResult?.txStatus !== TxStatus.SUCCESS) {
      throw new Error(`EVM write failed: ${writeResult?.errorMessage}`)
    }
    runtime.log(`HealthAlertRegistry.recordAlert tx: ${bytesToHex(writeResult.txHash || new Uint8Array(32))}`)
  // TODO: return a result string
  return 'ok'
}

function simpleHash(input: string): string {
  let hash = 0

  for (let i = 0; i < input.length; i++) {
    hash = (hash << 5) - hash + input.charCodeAt(i)
    hash |= 0
  }

  return `0x${Math.abs(hash).toString(16).padStart(8, "0")}`
}

// ─── Init ──────────────────────────────────────────────────────────────────

export function initWorkflow(config: Config) {

  network = getNetwork({
    chainFamily: 'evm',
    chainSelectorName: config.chainSelectorName,
    isTestnet: true,
  })
  if (!network) throw new Error(`Network not found: ${config.chainSelectorName}`)
  evmClient = new EVMClient(network.chainSelector.selector)
  const cronTrigger = new CronCapability()

  return [
    cre.handler(cronTrigger.trigger({ schedule: config.schedule }), on10MinHealthCheck),
  ]
}