import zkIllustration from "../assets/zkverify-illustration.svg";
import { HISTORICAL_ZKVERIFY_DEMO } from "../services/zkverify";

function shortenHash(value) {
  return `${value.slice(0, 12)} ··· ${value.slice(-10)}`;
}

function ZkVerifyCard() {
  const demo = HISTORICAL_ZKVERIFY_DEMO;

  return (
    <section id="verification" className="module-section proof-section chapter-section" data-chapter="05">
      <article className="glass-card proof-card">
        <div className="proof-card__visual"><img src={zkIllustration} alt="Groth16 verification network illustration" /></div>
        <div className="proof-card__content">
          <div className="chapter-question"><span>05</span><p>What is actually verified?</p></div>
          <div className="eyebrow eyebrow--violet"><span /> Historical zkVerify demo</div>
          <h2>Independent proof verification.</h2>
          <p>A separate Groth16 sample proof was submitted to zkVerify Volta and finalized independently. It is not generated by, or linked to, the current CRE workflow execution.</p>
          <div className="proof-facts">
            <div><span>Proof system</span><strong>{demo.proofSystem}</strong></div>
            <div><span>Network</span><strong>{demo.network}</strong></div>
            <div><span>Status</span><strong className="verified-text">{demo.status}</strong></div>
          </div>
          <div className="hash-list">
            <div><span>Statement hash</span><code title={demo.statementHash}>{shortenHash(demo.statementHash)}</code></div>
            <div><span>Transaction hash</span><code title={demo.transactionHash}>{shortenHash(demo.transactionHash)}</code></div>
          </div>
        </div>
      </article>
      <div className="chapter-transition" aria-hidden="true"><span /><i /></div>
    </section>
  );
}

export default ZkVerifyCard;
